name: Publish Documentation

on:
  push:
    branches: ["main"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: andreiio/rclone-action@v1
        name: Sync to Cloudflare R2
        with:
          args: sync docs s3:apibara-docs/docs/ --stats-one-line -v
        env:
          RCLONE_CONFIG_S3_TYPE: s3
          RCLONE_CONFIG_S3_PROVIDER: Cloudflare
          RCLONE_CONFIG_S3_ACL: private
          RCLONE_CONFIG_S3_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
          RCLONE_CONFIG_S3_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}

